#!/bin/sh
module="altpinfo"
device="altpinfo"
mode="666"

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod $module.ko $* || exit 1

# retrieve major number
#major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
major=42
echo "Major number for device altpinfo is: "$major

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/$device
mknod /dev/$device c $major 0
chgrp $group /dev/$device
chmod $mode /dev/$device
